version: "2"

services:
  nginx:
    image: nginx:1.11.1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  wordpress_base:
    image: wordpress:4.5.3
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wpsecret

  wordpress0:
    extends: wordpress_base
    environment:
      - WORDPRESS_DB_NAME=wpdb0
    volumes:
      - wordpress0_data:/var/www/html

  wordpress1:
    extends: wordpress_base
    environment:
      - WORDPRESS_DB_NAME=wpdb1
    volumes:
      - wordpress0_data:/var/www/html

  mysql:
    image: mysql:5.5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init.sh:/docker-entrypoint-initdb.d/mysql_init.sh
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wpsecret
      - MYSQL_DATABASE0=wpdb0
      - MYSQL_DATABASE1=wpdb1

volumes:
  wordpress0_data:
  wordpress1_data:
  mysql_data:
